name: 5mind-desktop
version: '1.1.9'  # overridden by git tag or whatever
summary: 5Mind Desktop Application
description: 5Mind Desktop Application.
base: core24
confinement: strict
grade: stable

platforms:
  amd64:

parts:
  electron-app:
    plugin: nil
    source: .
    override-build: |
      npm ci
      npx electron-builder --linux dir --x64
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      cp -rv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app/
      cp preload.js $SNAPCRAFT_PART_INSTALL/app/
      cp icon-256.png $SNAPCRAFT_PART_INSTALL/app/
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - mesa-vulkan-drivers
      - libvulkan1

apps:
  5mind-desktop:
    command: app/5mind-desktop
    plugs:
      - desktop
      - wayland
      - opengl
      - browser-support
      - network
      - audio-playback
