name: 5mind-desktop
version: '1.1.9'  
summary: 5Mind Desktop Application
description: 5Mind Desktop Application.
base: core24
confinement: strict
grade: stable

platforms:
  amd64:

parts:
  node:
    plugin: nil
    stage-snaps:
      - node/20/stable  
    override-pull: |
      craftctl default

  app-deps:
    plugin: nil
    source: .
    after: [node]
    override-build: |
      npm ci  # uses the staged Node/npm

  unpacked-app:
    plugin: nil
    source: .
    after: [app-deps]
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - mesa-vulkan-drivers
      - libvulkan1
    override-build: |
      npx electron-builder --linux dir --x64
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      cp -rv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app/
      cp preload.js $SNAPCRAFT_PART_INSTALL/app/
      cp icon-256.png $SNAPCRAFT_PART_INSTALL/app/

apps:
  5mind-desktop:
    command: app/5mind-desktop
    plugs:
      - desktop
      - wayland
      - opengl
      - browser-support
      - network
      - audio-playback
