name: 5mind-desktop
version: 1.1.9  
summary: 5Mind Desktop Application
description: 5Mind Desktop Application.
base: core24
confinement: strict
grade: stable

platforms:
  amd64:

parts:
  app:
    plugin: nil
    source: .
    override-build: |
      npm ci
      npx electron-builder --linux dir --x64
      cp -rv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/

stage-packages:
  - libgl1-mesa-dri
  - libglu1-mesa
  - mesa-vulkan-drivers
  - libvulkan1

apps:
  5mind-desktop:
    command: 5mind-desktop
    plugs:
      - desktop
      - wayland
      - opengl
      - browser-support
      - network
      - audio-playback
